---
title: "Figure experiment 2"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

### Reading libraries and parameters. Preparing the data

```{r, message=FALSE}
library(tidyverse)
library(cowplot)

list.files("R", full.names = TRUE) %>% walk(source)
source("graphical_parameters.R")
source("parameters.R")

load(file = "logdata/sym_averages_s_vs_d_best2.Rdata")
load(file = "logdata/sym_curves_s_vs_d_best2.RData")
load(file = "logdata/sym_par_s_vs_d_best_long2.RData")
load(file = "logdata/sym_par_s_vs_d_best_abs2.RData")
```

### Plotting psychometric functions
```{r}
theme_set(theme_classic(8))

p_fig_sup_exp2 <- ggplot() +
   facet_wrap(Participant~cond_per_block, 
              labeller = labeller(cond_per_block = 
                                    c(`1` = "1 reference per block", 
                                      `2`= "2 references per block"))) +
   geom_vline(xintercept = 0, size = size_line, lty = 2) +
   geom_hline(yintercept = 0.5, size = size_line, lty = 2) +
   geom_point(data = sym_averages_s_vs_d_best2 %>% 
                rename(Participant = subject), 
              aes(x = orientation, y = prob, color = best, shape = references)) +
   geom_line(data = sym_curves_s_vs_d_best2 %>% 
               rename(Participant = subject), 
             aes(x = x, y = y, color = best, lty = references)) +
  scale_color_manual(values = c("#377eb8", "#e41a1c", "#4daf4a","grey"),
                     breaks = c("zero", "sensory", "decision", "full"),
                     labels = c("No bias", "Sensory", "Decisional", "Sensory + decisional"))  +
    scale_shape_manual(breaks = c("TR", "BL"),
                     values = c(16, 3),
                     labels = c("Top", "Bottom")) +
    scale_linetype_manual(breaks = c("TR", "BL"),
                     values = c(1, 2, 1, 2),
                     labels = c("Top", "Bottom")) +
   scale_y_continuous(breaks = c(0, .5, 1)) +
   scale_x_continuous(breaks = -2:2, labels = c("-2", "-1", "0", "1", "2")) +
  coord_cartesian(xlim = c(-2.1, 2.1), ylim = c(0, 1.05))  +
   labs(x = text_orientation, y = text_prob_sym,
      color = text_best_model,
      shape = text_reference,
      lty = text_reference) +
    guides(
    color = guide_legend(order = 1),
    lty = guide_legend(order = 2),
    shape = guide_legend(order = 2)
  ) +
   theme(legend.position = "top",
         legend.box = "horizontal",
         legend.key.height = unit(0.8, "lines"),
         strip.background = element_blank(),
         axis.line = element_line(size = size_line), 
         axis.ticks = element_line(size = size_line),
         strip.text = element_text(margin = margin(0,0,0,0, "lines")))

p_fig_sup_exp2

```

```{r fig.height=4, fig.width=6}
p_sym_bias2 <- ggplot() + facet_wrap(~cond_per_block, 
                                    labeller = labeller(cond_per_block = 
                                    c(`1` = "1 reference per block", 
                                      `2`= "2 references per block"))) +
  geom_vline(xintercept = 0, size = size_line, lty = 2) +
  geom_hline(yintercept = 0, size = size_line, lty = 2) +
  geom_point(data = sym_par_s_vs_d_best_long2, 
             aes(x = p1, y = p2, color = best), alpha = .7) +
  scale_color_manual(values = c("#377eb8", "#e41a1c", "#4daf4a","grey"), 
                     breaks = c("zero", "sensory", "decision", "full"),
                     labels = text_labels_model)  +
  coord_equal(xlim = c(-1.5, 1.5), ylim = c(-1.5, 1.5)) +
  # xlim(-1.5, 1.5) +
  # ylim(-1.5, 1.5) +
  scale_x_continuous(breaks = seq(-1.5, 1.5, .5)) +
  scale_y_continuous(breaks = seq(-1.5, 1.5, .5)) +
  labs(x = text_sensory_bias, y = text_decisional_bias, 
       color = text_best_model) +
  theme(axis.line = element_line(size = size_line),
        axis.ticks = element_line(size = size_line),
        axis.title.y = element_text(hjust = 0.4), 
        strip.background = element_blank(),
          plot.margin = unit(c(0, 0, 0, 0), "cm"))
p_sym_bias2
```
  
```{r}

aov(abs_par ~ factor(cond_per_block) * parn + Error(factor(subject) / (factor(cond_per_block) * parn)), 
    data = sym_par_s_vs_d_best_abs2) %>% 
  summary()

t.test(abs_par ~ parn, data = sym_par_s_vs_d_best_abs2, paired = TRUE)


p_sym_bias_abs2 <- ggplot(data = sym_par_s_vs_d_best_abs2, 
             aes(x = parn, y = abs_par))+ #reorder(parn, desc(parn))
  facet_wrap(~cond_per_block,
               labeller = labeller(cond_per_block =
                                    c(`1` = "1 reference per block",
                                      `2` = "2 references per block"))) +
  geom_point(position = position_jitter(width = .15), 
             shape = 1, alpha = .5, size = .8) +
  stat_summary(fun.data = "mean_cl_boot",  geom = "crossbar", size = .15) + 
  labs(y = "Abs. value bias (deg)", x = "", title = "") +
  scale_x_discrete(breaks =c("Decisional\nbias","Sensory\nbias")) +
  scale_y_continuous(breaks = seq(0, 1, .5)) +
 # coord_cartesian(ylim = c(0, 1.2)) +
  theme(axis.line = element_line(size = size_line), 
        axis.ticks = element_line(size = size_line),
        strip.background = element_blank(),
        axis.title.x = element_blank())
      
p_sym_bias_abs2

```



```{r}

aov(abs_par ~ exp * parn + Error(subject / (parn)), 
    data = par_exp1_exp2) %>% 
  summary()

par_exp1_exp2 <- sym_par_s_vs_d_best_abs2 %>% 
  ungroup() %>% 
  select(-par, -best, -cond_per_block) %>% 
  mutate(exp = "exp2") %>% 
  bind_rows(
    sym_par_s_vs_d_best_abs %>% 
      ungroup() %>% 
  select(-par, -best, -vertical) %>% 
  mutate(exp = "exp1")
  ) %>% 
  mutate(parn_exp = paste0(parn, exp))

t.test(abs_par ~ exp, 
       data = par_exp1_exp2 %>% filter(parn == "Sensory\nbias"), 
       paired  = FALSE)

t.test(abs_par ~ exp, 
       data = par_exp1_exp2 %>% filter(parn == "Decisional\nbias"), 
       paired  = FALSE)

sym_par_s_vs_d_best_abs_ci2 <- sym_par_s_vs_d_best_abs2 %>% 
  ungroup() %>% 
  select(parn, abs_par) %>% 
  group_by(parn) %>% 
  nest() %>% 
  mutate(ttest= map(data, 
                    ~t.test(.$abs_par, 
                                 conf.int = TRUE) %>% 
                      tidy())) %>% 
  select(-data) %>% 
  unnest(ttest)



p_sym_bias_abs12 <- ggplot(data = par_exp1_exp2, 
             aes(x = factor(parn_exp, 
                             c("Sensory\nbiasexp1", "Decisional\nbiasexp1",
                               "Sensory\nbiasexp2", "Decisional\nbiasexp2")), 
                 y = abs_par))+ #
 # facet_wrap(~exp, labeller = labeller(exp = c(`exp1` = "Experiment 1", `exp2` = "Experiment 2"))) +
  geom_point(position = position_jitter(width = .15), 
             shape = 1, alpha = .5, size = .8) +
  geom_signif(comparisons = list(c("Sensory\nbiasexp1", "Decisional\nbiasexp1")),
              margin_top = .1,
              size = size_line,
              textsize = 4,
              annotations = "***") +
    geom_signif(comparisons = list(c("Sensory\nbiasexp2", "Decisional\nbiasexp2")),
              margin_top = .1,
              size = size_line,
              textsize = 4,
              annotations = "**") +
    geom_signif(comparisons = list(c("Sensory\nbiasexp1", "Sensory\nbiasexp2")),
              margin_top = .3,
              size = size_line,
              textsize = 2,
              annotations = "n. s.") +
      geom_signif(comparisons = list(c("Decisional\nbiasexp1", "Decisional\nbiasexp2")),
              margin_top = .45,
              size = size_line,
              textsize = 4,
              annotations = "*") +
    geom_crossbar(data = sym_par_s_vs_d_best_abs_ci %>% 
                    mutate(parn = if_else(parn == "Sensory\nbias", 
                                          "Sensory\nbiasexp1", 
                                          "Decisional\nbiasexp1")),
                size = .15,
                aes(x = parn, y = estimate, 
                    ymin= conf.low , ymax = conf.high)) +
      geom_crossbar(data = sym_par_s_vs_d_best_abs_ci2 %>% 
                    mutate(parn = if_else(parn == "Sensory\nbias", 
                                          "Sensory\nbiasexp2", 
                                          "Decisional\nbiasexp2")),
                size = .15,
                aes(x = parn, y = estimate, 
                    ymin= conf.low , ymax = conf.high)) +
  labs(y = "Abs. value bias (deg)", x = "Experiment 1          Experiment 2") +
  scale_x_discrete(breaks = c("Sensory\nbiasexp1", "Decisional\nbiasexp1",
                               "Sensory\nbiasexp2", "Decisional\nbiasexp2"),
                   labels = c("Sensory\nbias", "Decisional\nbias",
                               "Sensory\nbias", "Decisional\nbias")) +
  scale_y_continuous(breaks = seq(0, 2, .5), limits = c(0, 2.3)) +
 # coord_cartesian(ylim = c(0, 1.2)) +
  theme(axis.line = element_line(size = size_line), 
        axis.ticks = element_line(size = size_line),
        strip.background = element_blank())
      
p_sym_bias_abs12

```

```{r}
p_corr_exp2 <- ggplot(data = sym_par_s_vs_d_best_long2 %>% 
  select(subject, cond_per_block, p1) %>% 
  spread(cond_per_block, p1, sep=""),
  aes(x = cond_per_block1, y = cond_per_block2)) +
  geom_abline(slope = 1, intercept = 0, lty = 2, size = size_line) +
  geom_vline(xintercept = 0, lty = 2, size = size_line) +
  geom_hline(yintercept = 0, lty = 2, size = size_line) +
  geom_point(size = 2, alpha = .75) +
  scale_shape_manual(values = c(15, 16)) +
  geom_smooth(method = "lm", se = FALSE, size = .75, alpha = .75, color = "black") +
  coord_equal(xlim = c(-1.5, 1.5), ylim = c(-1.5, 1.5)) +
  theme(axis.line = element_line(size = size_line), 
        axis.ticks = element_line(size = size_line),
        legend.key.height = unit(.75, "lines"),
        legend.position = c(.9, .18)) +
  labs(title = "",
       x = expression(paste("Sensory bias ", bold("1"), " ref. per block (deg)")),
       y = expression(paste("Sensory bias ", bold("2"), " ref. per block (deg)"))) 

p_corr_exp2
```

```{r fig.height=10, fig.width=6}

p_bias_abs2 <- plot_grid(p_sym_bias2, 
                         p_sym_bias_abs12, 
                         nrow = 1, 
                         rel_widths = c(.65, .35),
                         labels = c("B", "C"))

p_fig_sup_3 <- plot_grid(p_fig_sup_exp2,
                         p_bias_abs2, 
                         ncol = 1, 
                         rel_heights = c(.79, .21),
                         labels = c("A"))
                       
save_plot('figures/figuresupplementary3.pdf', p_fig_sup_3, 
          base_width = two_column_width,
          base_height =  1.37 * two_column_width)
```


